### PR TITLE
[FLINK-30431][Connector/JDBC] JDBC Connector fails to reestablish the lost DB connect

### PR DESCRIPTION
**Pull request by Jiabao-Sun**
JDBC Connector fails to reestablish the lost DB connect.

### CODE REVIEW

**Review by MartijnVisser — COMMENTED** [review]
@Jiabao-Sun Can this behaviour be tested?

**Comment by MartijnVisser** [comment]
@Jiabao-Sun Can you rebase and use the new testing setup? @snuyanzin any thoughts on the actual PR fix itself?

**Comment by snuyanzin** [comment]
I would rather go with check if preparedstatment is closed or not rather than wrapping it in `try`...`catch`.
Is there anything blocking here to go that way?

**Comment by Jiabao-Sun** [comment]
> @Jiabao-Sun Can you rebase and use the new testing setup? @snuyanzin any thoughts on the actual PR fix itself?

Sorry for the late reply.
@MartijnVisser can you help trigger the CI?

**Comment by Jiabao-Sun** [comment]
> I would rather go with check if preparedstatment is closed or not rather than wrapping it in `try`...`catch`. Is there anything blocking here to go that way?

Thanks @snuyanzin for the suggestion.
As the JDBC Statement definition, If the database access error occurs we may also meet SQLException. 
image

**Comment by snuyanzin** [comment]
thanks for pointing to javadoc,
I've checked the javadoc for `java.sql.Statement#close` method as well e.g. [1]
and there is such statement
 >Calling the method close on a Statement object that is already closed has no effect. 

At the same time if we have a look at amazon redshift jdbc (based on trace from jira issue)
```
Caused by: com.amazon.redshift.util.RedshiftException: This connection has been closed.
    at com.amazon.redshift.jdbc.RedshiftConnectionImpl.checkClosed(RedshiftConnectionImpl.java:1095) ~[?:?]
    at com.amazon.redshift.jdbc.RedshiftConnectionImpl.cancelQuery(RedshiftConnectionImpl.java:1299) ~[?:?]
    at com.amazon.redshift.jdbc.RedshiftStatementImpl.cancel(RedshiftStatementImpl.java:1042) ~[?:?]
    at com.amazon.redshift.jdbc.RedshiftStatementImpl.close(RedshiftStatementImpl.java:748) ~[?:?]
```

it leads to `RedshiftConnectionImpl#checkClosed` [2]
```java
  protected void checkClosed() throws SQLException {
    if (isClosed()) {
      throw new RedshiftException(GT.tr("This statement has been closed."),
          RedshiftState.OBJECT_NOT_IN_STATE);
    }
  }
```

it violates the contracts mentioned in javadoc....
I would incline to consider that this is a redshift jdbc driver bug
[1] https://docs.oracle.com/javase/8/docs/api/java/sql/Statement.html#close--
[2] https://github.com/aws/amazon-redshift-jdbc-driver/blob/master/src/main/java/com/amazon/redshift/jdbc/RedshiftStatementImpl.java#L828-L833

**Comment by Jiabao-Sun** [comment]
Thanks @snuyanzin to point out this problem.
I think it is indeed the driver that violates this specification.
But back to this issue, do we need to fix it by capturing or wait for the redshift driver to fix this problem?

**Comment by snuyanzin** [comment]
short answer: i would suggest to wait for driver's fix

a bit more about what make me thinking like that
1. since there are multiple drivers might work with jdbc connector and each could have it's own issues it does not make sense to work around such issues on connectors level
2. there are lots of methods which could throw `SQLException` and at the same time handling of just one/part of them looks not consistent 
3. such wrapping in `try`...`catch` could potentially hide some other `SQLException` (not related to the current one) which for some other reasons could appear... Thus it could make it complex to analyze issue in case of any

**Pull request closed without merging**
