### PR TITLE
[hotfix] change FileSourceSplit to JdbcSourceSplit

### PR DESCRIPTION
**Pull request by caicancai**

### CODE REVIEW

**Comment by caicancai** [comment]
cc @RocMarshal @1996fanrui

**Review by RocMarshal — APPROVED** [review]
Thanks @caicancai for the catching
LGTM +1.

**Comment by caicancai** [comment]
@1996fanrui PTAL, thanks

**Review by 1996fanrui — APPROVED** [review]
Thanks for the fix, merging~

**Pull request merged**
