### PR TITLE
[FLINK-34259] Fix fails to compile with NPE on hasGenericTypesDisabled

### PR DESCRIPTION
**Pull request by Jiabao-Sun**
[FLINK-34259] Fix fails to compile with NPE on hasGenericTypesDisabled

### CODE REVIEW

**Comment by Jiabao-Sun** [comment]
CI passed locally https://github.com/Jiabao-Sun/flink-connector-jdbc/actions/runs/7709389700/job/21010504922

**Review by MartijnVisser — CHANGES_REQUESTED** [review]
@Jiabao-Sun This shouldn't be fixed in the JDBC connector, this appears to be a blocker for 1.19 since they shouldn't break interfaces

**Comment by Jiabao-Sun** [comment]
> IIUC, we're just failing the test not compiling, right?

Yes

**Comment by snuyanzin** [comment]
@reswqa can you please elaborate why it was decided to merge it here nevertheless it was mentioned by @MartijnVisser 
>@Jiabao-Sun This shouldn't be fixed in the JDBC connector, this appears to be a blocker for 1.19 since they shouldn't break interfaces

I feel like we need more info

**Comment by snuyanzin** [comment]
ok, thanks for clarification
i should have looked at jira as well

**Pull request closed without merging**
