### PR TITLE
[FLINK-34215] FLIP-377: Support fine-grained configuration to control filter push down for JDBC Connector

### PR DESCRIPTION
**Pull request by Jiabao-Sun**
This improvement implements [FLIP-377 Support fine-grained configuration to control filter push down for Table/SQL Sources](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=276105768)

### CODE REVIEW

**Comment by eskabetxe** [comment]
@Jiabao-Sun could you please rebase

**Comment by Jiabao-Sun** [comment]
Thanks @eskabetxe for the reminder.
Rebased.

**Review by eskabetxe — APPROVED** [review]
@RocMarshal can you take a look?

**Review by RocMarshal — APPROVED** [review]
Thanks @Jiabao-Sun for the contribution and @Jiabao-Sun for the review.
LGTM +1.

**Review by 1996fanrui — COMMENTED** [review]
Thanks @Jiabao-Sun for the contribution, and thanks @eskabetxe and @RocMarshal for the review!

Merging~

**Pull request merged**
