### PR TITLE
[FLINK-30790] Add DatabaseExtension with TableManaged for testing

### PR DESCRIPTION
**Pull request by eskabetxe**
## What is the purpose of the change

Added DatabaseExtension, basically is a junit extension that start, clean and stop the containers, so only one container for database is started for all tests that use it..
The tests could provide the tables that want the extension to manage with TableManaged.

## Brief change log

- Add DatabaseExtension and TableManaged
- Refactor all tests that use containers to use this
- Clean and refactor tests that are extended or duplicate by database tests
- Fixed JdbcExactlyOnceSinkE2eTest that creates a lot of instability on tests (mainly with oracle test)

## Verifying this change

All tests are maintained (some added) and must be passing

## Does this pull request potentially affect one of the following parts:

This don't affect nothing at is pure tests change

## Documentation

JavaDocs where apply

### CODE REVIEW

**Comment by eskabetxe** [comment]
@MartijnVisser, @snuyanzin could you help here?

**Comment by MartijnVisser** [comment]
@eskabetxe I see that the CI fails with `WARNING: ConnectionID:1 ClientConnectionId: 012104c1-3f1a-4a4b-88af-5f623f5288e9 Prelogin error: host localhost port 32801 Unexpected end of prelogin response after 0 bytes read`. https://github.com/apache/flink-connector-jdbc/actions/runs/4806312954/jobs/8553681571?pr=22#step:13:369 - Can that be fixed?

**Comment by eskabetxe** [comment]
@MartijnVisser all tests pass now

**Comment by eskabetxe** [comment]
@MartijnVisser any news for merging this?

**Review by MartijnVisser — APPROVED** [review]
@eskabetxe Thanks for this. I've skimmed over the changes and they look good to me. Given your expertise on the JDBC connector, I'll merge this

**Pull request merged**
