### PR TITLE
[FLINK-35862] Fixed incorrect words in the Chinese documentation

### PR DESCRIPTION
**Pull request by liboshuai01**

### CODE REVIEW

**Comment by liboshuai01** [comment]
Hi, @reswqa , could you please tell me why there are checks errors? Is it because of the code changes I made this time?

**Comment by liboshuai01** [comment]
> LGTM, thanks.

Hi, could you please tell me why there are checks errors? Is it because of the code changes I made this time?

**Comment by liboshuai01** [comment]
Hi, @reswqa , you help me merge the code?😊

**Comment by liboshuai01** [comment]
Hi, @reswqa , Can you help me merge the code?😊

**Review by reswqa — COMMENTED** [review]
CI passed, merging...

**Pull request merged**
