### PR TITLE
[FLINK-30357][doc] Wrong link in connector/jdbc doc.

### PR DESCRIPTION
**Pull request by GOODBOY008**
Link https://issues.apache.org/jira/browse/FLINK-30357.

### CODE REVIEW

**Review by MartijnVisser — APPROVED** [review]
@GOODBOY008 Thanks for the fix :)

**Comment by MartijnVisser** [comment]
@GOODBOY008 Can you also create a backport towards the `v3.0` branch?

**Comment by GOODBOY008** [comment]
> @GOODBOY008 Can you also create a backport towards the `v3.0` branch?

@MartijnVisser This repo document will push to website? And I'm want to know this should commit to `flink` repo too?

**Comment by MartijnVisser** [comment]
> @MartijnVisser This repo document will push to website? And I'm want to know this should commit to `flink` repo too?

Yes, when the JDBC connector has been released (the vote is ongoing) then the documentation will be switched from the Flink repo to this repo. So at this moment, we need to fix it in both

**Pull request merged**
